---
- hosts: workstation

  tasks:
    - name: install box-sync
      mac_pkg: pkg_type=app
               url=https://e3.boxcdn.net/box-installers/sync/Sync+4+External/Box%20Sync%20Installer.dmg
               archive_type=dmg archive_path=Box Sync.app
      sudo: yes

